default: &default
  omniauth:
    facebook:
      id: fbid
      sec: fbsecret
      callback_url: 'https://example.com/auth/auth/facebook/callback'
    linkedin:
      key: lnkey
      sec: lnsecret
    google:
      id: gpid
      sec: gpsecret
  smtp:
    address: smtp.somewhere.com
    port: 25
    domain: example.com
    user: user
    pass: password
    auth: plain
  devise:
    mailer:
      sender: please-change-me-at-config-initializers-devise@example.com

development:
  <<: *default
  base_url: 'http://localhost:3000'

test:
  <<: *default
  base_url: 'http://localhost:3000'
