common: &default_settings
  license_key: <%= ENV['NRKEY'] %>
  app_name: Datoca
  log_level: info

development:
  <<: *default_settings
  app_name: Datoca (Development)
  developer_mode: true

test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings
